series: GLFW Graphics
title: Standard 3D
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program serves to demonstrate what a basic 3D OpenGL program looks like.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Basic 2d OpenGL program
